// Generated by generate.mjs: this package's API on each marketplace.
export const API_TITLE = 'Link Preview and URL Metadata';
export const API_MARKET_SLUG = 'link-preview';
export const RAPIDAPI_HOST = 'link-preview-and-url-metadata2.p.rapidapi.com';
